# Setup
title:        ArchGuard
baseurl:      ""
paginate:     1
locale:       "zh-CN"

# About/contact
author:
  name:       ThoughtWorks
  url:        https://archguard.org

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown