# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: ""
subtitle: Everything as code, every code could be guard
email:
logo: "/assets/images/Logo-Shield.png"
og_image: /assets/images/Logo-Shield.png
description: Everything as code, every code could be guard
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://archguard.org/" # the base hostname & protocol for your site, e.g. http://example.com

author:
  name: ArchGuard Team
  url: https://www.archguard.org/

repository: "archguard/archguard.org"

# Build settings
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
# theme: minimal-mistakes-jekyll
# minimal_mistakes_skin: dirt
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

include:
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  - tmp
  - .idea
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"


# Build settings
markdown: kramdown
permalink: /:categories/:title/
# Outputting
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Collections
collections:
  #  map to defaults.scope.type
  models:
    output: true
    permalink: /:collection/:path/
  manuals:
    output: true
    permalink: /:collection/:path/
  supports:
    output: true
    permalink: /:collection/:path/

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      read_time: true
      related: true
  - scope:
      path: ""
      type: supports
    values:
      layout: single
  - scope:
      path: ""
      type: manuals
    values:
      layout: single
  - scope:
      path: ""
      type: models
    values:
      layout: single
  - scope:
      path: ""
      type: supports
    values:
      layout: single
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
